source 'https://github.com/CocoaPods/Specs.git'

target 'PFLinkedInUtils', :exclusive => true do
  pod "PFLinkedInUtils", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PFLinkedInUtils", :path => "../"

  
end
