language: objective-c

osx_image: xcode8.3

script:
- xcodebuild -workspace Example/PFLinkedInUtils.xcworkspace -scheme PFLinkedInUtils -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" -configuration Debug -enableCodeCoverage YES clean build test
